### ISSUE TITLE
estas--esta

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1101]
https://github.com/rdrg109/subtitles-npcr/blob/4d007f0d7f48ebda5b35791f3cf6b5f2267f794b/sentences/45-text-1.yaml#L306C34-L306C39

**Comment by rdrg109** [comment]
solves

**Comment by fhxshrs** [comment]
@rdrg109 这句话里有两个esta哦。

**Comment by rdrg109** [comment]
a9163b2
