### ISSUE TITLE
energy--responsibility

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1105]
https://github.com/rdrg109/subtitles-npcr/blob/c9c180e60192e590b966c9d3e831a4294aa25b54/sentences/45-text-2.yaml#L120C11-L120C17

**Comment by rdrg109** [comment]
This was fixed in 74d679b1be43ccd904fb797c02b84296a37b6f49. The current translation is shown below.

https://github.com/rdrg109/subtitles-npcr/blob/e0339b82a61640d87c998f4c704aaf80b8cd10b4/sentences/45-text-2.yaml#L124-L128
