### ISSUE TITLE
Little friend -- Kid

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1113]
https://github.com/rdrg109/subtitles-npcr/blob/1c56c5a8099a2253b50c5d443937efd985125c82/sentences/46-text-1.yaml#L307-L311

**Comment by rdrg109** [comment]
@fhxshrs I have a question: In China, I know that people call kids that are not their children 小朋友. Would it sound weird if someone call a kid 孩子? If not, what's the most common word that is used to refer to a kid?

**Comment by fhxshrs** [comment]
@rdrg109  我觉得“孩子”更多的是用于称呼自己的孩子，像hijos；而“小朋友”则是叫和自己没有血缘关系的年纪很小的人。

**Comment by rdrg109** [comment]
@fhxshrs Thanks for the explanation! Then, I think the current translation is suitable in this context.

https://github.com/rdrg109/subtitles-npcr/blob/e3723337b618101698eeef757ad65ff71c578385/sentences/46-text-1.yaml#L317-L321
