### ISSUE TITLE
stay with the student group -- be united with your classmates

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1120]
https://github.com/rdrg109/subtitles-npcr/blob/bab51df130ecfd01b9f213c863875188d028fc4a/sentences/46-text-2.yaml#L253-L257

**Comment by rdrg109** [comment]
I wasn't sure of the definition of 团结, so I checked the definition in two dictionaries and now I'm sure. I introduced your suggestion: 9c7e138.

# 现代汉语词典（第7版）(p. 1329)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/406384b5-c1da-4cdf-9782-571296430e2f)

❶〈动〉为了集中力量实现共同理想或完成共同任务而联合或结合：～朋友，打击敌人｜～就是力量。
❷〈形〉齐心协力，结合紧密；和睦：邻里～｜大家很～。

# 现代汉语规范词典（第2版）(p. 1332)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/f499e844-66aa-4731-9253-43cfd66a9088)

❶〈动〉联合一致，紧密合作▷～起来｜～大多数。
❷〈形〉关系融洽，相处和谐▷～这个集体很～。
