### ISSUE TITLE
at the top -- on that

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#1121]
https://github.com/rdrg109/subtitles-npcr/blob/bab51df130ecfd01b9f213c863875188d028fc4a/sentences/46-text-2.yaml#L285-L289

**Comment by rdrg109** [comment]
@fhxshrs I think "... on that" is not grammatically correct. If we say "on that" we need to add a noun after it. For example,

> If I agreed to that and **signed on that dotted line**, it meant that the Australian Opera would be able to get me out on an assisted passage.” [(retrieved from The Guardian)](https://www.theguardian.com/music/2015/jul/17/conductor-mark-elder-i-owe-australia-my-career)

> ..., the Prime Minister obviously hopes to replicate the atmosphere that produced the agreement **signed on that long Good Friday last year**, ... [(retrieved from The Guardian)](https://www.theguardian.com/uk/1999/jun/27/northernireland.guardiancolumnists)

> ..., she wrote: "I **signed on that document**. This is a fact that I can't change, even if I want to." [(retrieved from BBC)](https://www.bbc.com/news/world-africa-57486959).

> "I think I had one day down in Bournemouth," he explained. "I was supposed to come down and look at the training ground and stadium. I **signed on that day** and I wasn't allowed home. [(retrieved from BBC)](https://www.bbc.com/sport/football/34282004)

For this reason, I've used "... on it" instead: 4b8c2df .

I've opened a discussion #1131 on "me and her" being grammatically correct.
