### ISSUE TITLE
friend

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#38]
https://github.com/rdrg109/npcr-subtitles/blob/6cb024dfc2e3453d1fb5674eae17cf5b187b8c89/sentences/44-1.yaml#L39

**Comment by rdrg109** [comment]
Estoy de acuerdo contigo, la traducción debería ser "friend". Ya lo corregí: 24fada1

Al inicio, yo estaba confundido, porque la misma persona luego dice esto:

https://github.com/rdrg109/npcr-subtitles/blob/2849f67c77e9714b418a9b6b63cc81c839a35dab/sentences/44-1.yaml#L46-L50

Luego, me acordé que "这位外国朋友" se refiere a una persona. Si fuesen dos personas, entonces sería "这些外国朋友".

**Comment by fhxshrs** [comment]
因为王小云是中国人，所以老板才会说“这位外国朋友（指林娜）”，而在后文又说“你们（指林娜和王小云）看”。
