### ISSUE TITLE
我不太确定这句话的准确翻译是什么，但它这个翻译应该是不太准确的。

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#43]
https://github.com/rdrg109/subtitles-npcr/blob/b5b5dd981582754b6ac44cf6a816ce387cda1701/sentences/44-1.yaml#L74

**Comment by rdrg109** [comment]
I think the translation is incorrect. This is explained in the book. 

English version (2nd edition):

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/db1418c2-3ab5-432d-bf26-7e576399720a)

Spanish version:

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/a055678a-b238-4c0a-ba0a-da5ae5fab272)

This expression is also explained in this website: [Polite Expressions and Affirmative Expressions](https://www.ccjk.com/polite-expressions-and-affirmative-expressions/).

I've already done the changes: 17de6c0 (English) and 426815c (Spanish).
