### ISSUE TITLE
这句话我也不太确定怎么翻译比较准确，但是它这个翻译不太准确。

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#49]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L144C9-L144C9

**Comment by rdrg109** [comment]
我同意，这个翻译不太准确。

@fhxshrs 我认为这个更好：“You can choose and take a look at them as you wish”。你同意吗？

**Comment by fhxshrs** [comment]
同意

**Comment by rdrg109** [comment]
Done! 0c923c8f2c32c69a457950a041f9a49352caa9cb
