### ISSUE TITLE
We get our goods directly from the factory.

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#50]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L169

**Comment by rdrg109** [comment]
Done! 3446562bcfe20d15b25a8a3b56da402f189bb42a

For reference, this is an screenshot of the English version (2nd edition).

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/4b5d81dc-2ec9-46ef-a75b-b294e7441031)
