### ISSUE TITLE
If they weren't be purchased directly

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#51]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L174

**Comment by fhxshrs** [comment]
同意

**Comment by rdrg109** [comment]
Done! 4848bb0f6f8020f5e7a9b26f828fb6f0b5e2319b
