### ISSUE TITLE
？--。

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#52]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L202

**Comment by rdrg109** [comment]
视频上的字幕：

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/5f38e1ad-0b70-4788-aa21-c524c8665620)

课文里：

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/39faa823-c67c-4168-9a04-75030caca5d8)

有可能视频上的本来字幕有错误。怎么办？

@fhxshrs 从老板的语气你认为是问号还是句号？我们这样决定吧。

https://github.com/rdrg109/subtitles-npcr/assets/74389646/72f04a84-582c-4bca-aea8-13b28cd280de

**Comment by fhxshrs** [comment]
从视频的语气来看，老板的这句话语气是上扬的，所以用“？”其实没问题，也是在征求林娜的意见，那这里就保留问号吧。

**Comment by rdrg109** [comment]
I just checked the audio from the book and noticed that the tone in the book is different than the tone in the video.

音频（课文）：

[a.webm](https://github.com/rdrg109/subtitles-npcr/assets/74389646/cb1708df-5118-41e8-9f2b-f18ecc47111f)

视频：

[b.webm](https://github.com/rdrg109/subtitles-npcr/assets/74389646/2029186f-ebab-4abb-b4ce-1cb0f37bc4f5)

We have already decided that 问号 should be shown, but from the tone of the audio I believe that it should show 句号. So, we can show 问号 in the video, but 句号 in the audio. @fhxshrs Do you agree with me?

**Comment by fhxshrs** [comment]
同意

**Comment by rdrg109** [comment]
Done! dc28088
