### ISSUE TITLE
Give me a price.

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#53]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L204C4-L204C4

**Comment by rdrg109** [comment]
Let's first solve the issue #52 to decide if there should be one or two versions for this

**Comment by rdrg109** [comment]
Done! dc280888eb76f5eab059b2ab72610079bc9647e5

The final decision was to have one version for the book (with period) and one for the video (with question mark). The decision was drawn on the tone of the speakers in the audios.
