### ISSUE TITLE
for such -- in this way

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#59]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L224C7-L224C23

**Comment by rdrg109** [comment]
I think "for such" is more suitable, but we need to add "price".

The expression "selling in this way" can have lots of meanings (e.g. the location of the store, the inconveniences that the seller might have, etc.). "selling for such price" is more specific.

**Comment by fhxshrs** [comment]
同意

**Comment by rdrg109** [comment]
I had accidentally closed this issue. I have improved taken this issue in consideration in e6d0586.
