### ISSUE TITLE
The price I sell now is almost the purchase price

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#60]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L229

**Comment by rdrg109** [comment]
I think saying "replenishment price" is more specific than "purchase price". The expression "purchase price" can refer to the price from the perspective of the client, so it can be confusing.

This is [the meaning of "replenish" in Longman Dictionary](https://www.ldoceonline.com/dictionary/replenish):

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/a48db518-478d-4b0a-a6a5-a10326c1e07e)

@fhxshrs Do you agree with me?

**Comment by fhxshrs** [comment]
看了你的解释，我觉得"replenishment price"更多的是指“补货价”，它和“进货价”还是有细微的区别，所以我不知道英语更贴切的翻译应该是什么。

**Comment by rdrg109** [comment]
@fhxshrs  你能解释一些“补货价”和“进货价”的区别吗？这样我可以准确地想起来英语的翻译。

**Comment by fhxshrs** [comment]
“进货”指的是商家从生产厂家那儿以较低的价格购入货物；而“补货”是指在已经购入了一部分货物的情况下，再次购入货物，对库存进行补充。

**Comment by rdrg109** [comment]
In the dialogue, "进货价" is mentioned, so let's focus on this word.

> “进货”指的是商家从生产厂家那儿以较低的价格购入货物；

The following list contains English words that have a similar meaning to this definition that you have mentioned. Definitions retrieved from [Longman Dictionary](https://www.ldoceonline.com). 

+ "replenish": to put new supplies into something, or to fill something again
+ "restock": to bring in more supplies to replace those that have been used
+ "purchase": to buy something
+ "acquire":  to obtain something by buying it or being given it

I think none of these words express the same meaning that you have mentioned. I think we can express that meaning by saying

> 我现在卖的价，**几乎就是进货价，**

> The price I’m selling for at the moment, **it’s almost the price with which I buy to manufacturers,**

@fhxshrs Do you agree with me?

**Comment by rdrg109** [comment]
Done! dac4a169c86f6b645e82ededb78f7915e3ae5be5
