### ISSUE TITLE
Why did you say 98 yuanes,

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#66]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L279C26-L279C33

**Comment by rdrg109** [comment]
Let's decide whether it should be "yuanes" or "dollars" by discussing this in https://github.com/rdrg109/subtitles-npcr/issues/47.

**Comment by rdrg109** [comment]
Done! 2371d00a28161896c4214f322c446e7e46fefed7. For the record, see final decision in https://github.com/rdrg109/subtitles-npcr/issues/47#issuecomment-1643928395
