### ISSUE TITLE
Anyway

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#69]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L294C22-L294C22

**Comment by rdrg109** [comment]
I agree with you. In this context, "不管怎么说" have the same meaning of "Anyway".

Another translation could be "Regardless of how you put it", this translation is longer, but convey the same meaning and would allow students know that 不管 have the same meaning as "regardless of". @fhxshrs do you agree with me?

**Comment by fhxshrs** [comment]
同意

**Comment by rdrg109** [comment]
Done! b3a48c3a173b6a247b1dc290b8bad6162e742449 I wrote "say" instead of "put" because they both have the same meaning in this context and, when highlighting words, we can match "say" with "说".
