### ISSUE TITLE
and I didn't ask you for a penny more.

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#70]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L299

**Comment by rdrg109** [comment]
Done! 5b072073bf86c08263b97204d3e5dd542d328731

**Comment by rdrg109** [comment]
等一下、我有一个问题：在“我也没有多要您一分钱。”中，“一分钱”指的是 0.01 元对吗？如果是这样我觉得“penny”不适合，因为“penny”指的是英国、美国、加拿大的钱而不指的是中国的钱（[在 Longman Dictionary 上的意义](https://www.ldoceonline.com/dictionary/penny)）。

![2023-07-19_12-43](https://github.com/rdrg109/subtitles-npcr/assets/74389646/ba833c27-d42a-48e0-bc41-2aa822f0fd04)

所以翻译应该是：“I didn't ask you for a cent more of a yuan. ”。 @fhxshrs  你同意吗？

**Comment by fhxshrs** [comment]
同意

**Comment by rdrg109** [comment]
Done! 79226d54774340f86fa686f9dafad1e85a5efb1a
