### ISSUE TITLE
what you buy is not really what is being sold -- the one who buys is not as shrewd as the one who sells

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#71]
https://github.com/rdrg109/subtitles-npcr/blob/6c9e0c6561e43bfafdf1378a8c8092c387173d8a/sentences/44-1.yaml#L334C32-L334C77

**Comment by rdrg109** [comment]
课文里有：“从南京到北京，买的没有卖的精。”

中文：A 比 B 精。（A 的级别 > B 的级别）
英语翻译："A is [smarter]/[more shrewd] than B" （A 的级别 = B 的级别）

中文：A 没有 B 精。（A 的级别  <= B 的级别）
英语翻译："A is not [smarter]/[more shrewd] than B" （A 的级别  <= B 的级别）

"A is as shrewd as B" 表达A 的精级别 = B 的精级别，所以我认为“A is not [smarter]/[more shrewd] than B”更适合， @fhxshrs  你同意吗？

**Comment by fhxshrs** [comment]
同意

**Comment by rdrg109** [comment]
Done! fb16ac4b8a3d26b6850f1d85c4a99c1b94ca14a5
