### ISSUE TITLE
What does 京剧团 mean?

### ISSUE THREAD

**Issue by rdrg109** [rdrg109/subtitles-npcr#73]
https://github.com/rdrg109/subtitles-npcr/blob/ea3c45fa6e767252d41e39d7bc61de59e6be56af/sentences/30-2.yaml#L57

As far as I understand, the character 团 refers to a group of people, but I still have a question: When 马大为 says "京剧团怎么到这儿来唱呢？" is he referring to a unique group of people or he refers to any group of people that plays 京剧团?

**Comment by fhxshrs** [comment]
any group of people that plays 京剧

**Comment by fhxshrs** [comment]
是的，是我不够仔细，京剧团应该指A group of professional people who sing Beijing opera，但是并不指具体某一个团体。
