### ISSUE TITLE
"but" or "well" for 不过?

### ISSUE THREAD

**Issue by rdrg109** [rdrg109/subtitles-npcr#76]
https://github.com/rdrg109/subtitles-npcr/blob/3936ab00c4123e6ebfc6a89e50c42fedfe26a59c/sentences/44-1.yaml#L76-L80

@fhxshrs 你觉得呢？

**Comment by fhxshrs** [comment]
but吧

**Comment by rdrg109** [comment]
Done! bb4a4d2
