### ISSUE TITLE
her child is currently in the school year

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#82]
https://github.com/rdrg109/subtitles-npcr/blob/4905cef6c4c5326e03470cf75f4f055425e8b8d2/sentences/44-2.yaml#L34C6-L34C42

To be honest, I'm not sure about my translation.

**Comment by rdrg109** [comment]
Definitely, the current translation is not grammatically correct.

https://github.com/rdrg109/subtitles-npcr/blob/c128f0b659e44130b87749e3e6f5569061e90a90/sentences/44-text-2.yaml#L39

Regarding the translation that you proposed, I was having doubts whether it's correct to say that "(someone) is in the school year". I searched some examples on the Internet and I found this

> t cannot be fair that many of the youngest kids **in the school year** are left on the sidelines. (Retrieved from [The Guardian](https://www.theguardian.com/sport/2006/nov/29/athletics.gdnsport3))

> As with Monika, there’s slight confusion over Pooja’s real age. She is **in the school year for 14 to 15-year-olds**, though she tells me she’s a couple of years older. (Retrieved from [BBC](https://www.bbc.com/news/resources/idt-sh/indian_child_marriage))

However, I still feel that this style of writing is not common to Spanish speakers, so I would prefer this translation: "her child is currently attending school."

Let's ask some other Peruvians what they think: (1) or (2)

1. "her child is currently in the school year"
2. "her child is currently attending school"

**Comment by rdrg109** [comment]
@nataliapalomares ¿Qué traducción prefieres (1) o (2)?

**Comment by nataliapalomares** [comment]
@rdrg109 Yo creo que la traducción más adecuada es la 2. Porque en el primer caso se enfatiza el grado en el que se encuentra, además por lo que veo en los ejemplos se usa en un contexto más especifico. En cambio en el segundo caso, lo que expresa es el hecho de que su hijo va a la escuela.
Esto tiene más sentido en el texto ya que está listando todos los motivos por los que la situación económica del personaje es complicada.

**Comment by rdrg109** [comment]
@nataliapalomares Estoy de acuerdo contigo, parece ser que la expresión "in the school year" se usa en contextos más específicos. En el texto, solo queremos enfatizar la situación actual de que los niños van a la escuela.

¡Listo! 8cb6895
