### ISSUE TITLE
didn’t tell her -- either said

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#83]
https://github.com/rdrg109/subtitles-npcr/blob/c128f0b659e44130b87749e3e6f5569061e90a90/sentences/44-text-2.yaml#L56-L60

**Comment by rdrg109** [comment]
Done! 0504844

The structure that you have quoted is related to the structure that also appear in

https://github.com/rdrg109/subtitles-npcr/blob/c128f0b659e44130b87749e3e6f5569061e90a90/sentences/43-text-1.yaml#L86-L90

I looked some information on the Internet and found [this article](https://resources.allsetlearning.com/chinese/grammar/Expressing_the_only_two_possibilities) that explains this grammar rule. I didn't know this, so I learned something new, so I feel happy.

>  To describe a situation as being one of only two possibilities, you can use the structure "不是⋯⋯就是⋯⋯" (bù shì... jiùshì...), which literally means, "if it's not... it's...."
