### ISSUE TITLE
or that she was a bit uneducated.

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#84]
https://github.com/rdrg109/subtitles-npcr/blob/4905cef6c4c5326e03470cf75f4f055425e8b8d2/sentences/44-2.yaml#L59

**Comment by rdrg109** [comment]
@fhxshrs The problem with using the translation "or that she was a bit uneducated" is that it makes it difficult to group the words. If we use "uneducated", we would need to show `uneducated` and `文化低` in the same group, but I believe that it's better to show `文化` and `低` in different groups, so a better translation could be: "or that her cultural level was a little bit low"

Do you agree with me?

**Comment by fhxshrs** [comment]
同意
