### ISSUE TITLE
more of these -- some more

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#85]
https://github.com/rdrg109/subtitles-npcr/blob/4905cef6c4c5326e03470cf75f4f055425e8b8d2/sentences/44-2.yaml#L99-L99

**Comment by rdrg109** [comment]
We have two possible translations

(1) "If you sell more of these stationery": The speaker recommends selling more quantity of the same product that he/she is currently watching.
(2) "If you sell some more stationery": The speaker recommends selling products of different type that he/she's is not currently watching.

@fhxshrs You recommended using (2). Do you agree with me that the speaker want to express that meaning?

**Comment by fhxshrs** [comment]
同意，课文想表达的就是第二种意思：这家店最初只卖玩具，所以别人建议她也可以再卖一些文具。

**Comment by rdrg109** [comment]
Then, the translation should be: "If you sell some stationery," (without "more"). When 老先生 said this to 胖阿姨, 胖阿姨 was only selling toys.

@fhxshrs Do you agree with me?

**Comment by fhxshrs** [comment]
同意

**Comment by rdrg109** [comment]
Done! 6e91307
