### ISSUE TITLE
collect even one extra cent from -- overcharged

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#87]
https://github.com/rdrg109/subtitles-npcr/blob/4905cef6c4c5326e03470cf75f4f055425e8b8d2/sentences/44-2.yaml#L144C44-L144C76

**Comment by rdrg109** [comment]
Done! 3d1234b

The verb in infinitive is "overcharge", so we say "would overcharge". We don't say "would overcharged".
