### ISSUE TITLE
the child -- children

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#89]
https://github.com/rdrg109/subtitles-npcr/blob/4905cef6c4c5326e03470cf75f4f055425e8b8d2/sentences/44-2.yaml#L154C29-L154C33

**Comment by rdrg109** [comment]
Let's finish the discussion in https://github.com/rdrg109/subtitles-npcr/issues/88#issuecomment-1657071450 , before continuing with this change.
