### ISSUE TITLE
Should the pinyin of 都 be dōu instead of doū in all these sentences?

### ISSUE THREAD

**Issue by rdrg109** [rdrg109/subtitles-npcr#904]
@Felicia0616 in #895 and in #892 have found two errors related to the pinyin of the character `都`.

This motivated me to write some Python code to list all the groups whose `zh-hans` field contain the character `都` and whose `pinyin` field contain `doū`. The results are shown below. I wish someone familiar with pinyin could confirm that in all those groups, the pinyin of the character shouldn't be doū, but it should be dōu.

```
- id: 41c6ed34-4e94-4f5c-922e-9a4934c5d030
  zh-hans: 真不知道你每天都在想些什么。
  pinyin: Zhēn bù zhīdào nǐ měitiān doū zài xiǎng xiē shénme.
- id: 6cf3ea86-958c-4b2f-ae2b-0d0e1a9092fa
  zh-hans: 这两天都是(1:坏:10)(2:消息:11)。
  pinyin: Zhè liǎng tiān doū shì (1:huài) (2:xiāoxi).
- id: c13fd1ae-7484-4a33-a25c-7e106d36b2e2
  zh-hans: 刚来的时候你说过，如果每天都让你吃(1:中餐:17)，
  pinyin: Gāng lái de shíhou nǐ shuōguò, rúguǒ měitiān doū ràng nǐ chī (1:zhōngcān),
- id: 275226c4-7945-40b3-a873-2da73926e720
  zh-hans: 是啊。我们从小到大都这样做。
  pinyin: Shì a. Wǒmen cóngxiǎo dào dà doū zhèyàng zuò.
- id: 41510ad8-ebdb-42e4-a5fe-7af801f90f37
  zh-hans: 我觉得都很好。我爸爸妈妈他们也都是这样。
  pinyin: Wǒ juéde dōu hěn hǎo. Wǒ bàba māmā tāmen yě doū shì zhèyàng.
- id: f717a5e1-b607-4966-9ef8-1047fa16b530
  zh-hans: 人们常说，如果你每天都认认真真地练，
  pinyin: Rénmen cháng shuō, rúguǒ nǐ měitiān doū rènrèn zhēnzhēn de liàn,
- id: 339eb456-e106-43bd-8e0c-c21e2a9d0d13
  zh-hans: 也都是些老人。
  pinyin: yě doū shì xiē lǎorén.
- id: fb71b287-46b4-405a-a23d-ebbdd156d4b3
  zh-hans: 因为爱好一样，不认识的人也都成了朋友。
  pinyin: Yīnwèi àihào yīyàng, bù rènshi de rén yě doū chéngle péngyǒu.
- id: b6540d97-ba6f-453d-a7be-41393f772eb8
  zh-hans: 你每天都六点起床去锻炼，
  pinyin: nǐ měitiān doū liù diǎn qǐchuáng qù duànliàn,
- id: 12ceff94-285e-4846-b04a-cd71a869dd71
  zh-hans: 黄山的松树和山峰也都很有特色。
  pinyin: Huángshān de sōngshù hé shānfēng yě doū hěn yǒu tèsè.
- id: f1da4184-d727-4053-a7fc-b08e9e131bda
  zh-hans: 它每天都在热情地欢迎游黄山的朋友们。
  pinyin: tā měitiān doū zài rèqíng de huānyíng yóu Huángshān de péngyǒumen.
- id: 74cd1fc2-6ae2-4277-ac4d-b83e30628209
  zh-hans: 他们也都很好。哥哥现在在一个中学打工，
  pinyin: Tāmen yě doū hěn hǎo. Gēgē xiànzài zài yīgè zhōngxué dǎgōng,
- id: 5d134402-fe07-43bd-9be5-a3c55edbaa70
  zh-hans: 他来过两次，可是我都不在。
  pinyin: Tā láiguò liǎng cì, kěshì wǒ doū bùzài.
- id: 2702e021-5978-4c2d-9701-b040e3d27f6a
  zh-hans: 现在我们都学习汉语，也都是汉语系的学生。
  pinyin: Xiànzài wǒmen dōu xuéxí Hànyǔ, yě doū shì Hànyǔxì de xuéshēng.
```

The Python code that was used to get these results are shown below.

```python
import os
import yaml

dir = './subtitles-new-practical-chinese-reader/sentences'

os.chdir(dir)
files = os.listdir(dir)

for file in files:
    with open(file) as f:
         data = yaml.safe_load(f)
         for obj in data:
             if '都' in obj['zh-hans'] and 'doū' in obj['pinyin']:
                 print(f"""- id: {obj['id']}
  zh-hans: {obj['zh-hans']}
  pinyin: {obj['pinyin']}""")
```

**Comment by Felicia0616** [comment]
是的，这些“都”的拼音是错的，拼音中不把声调放在“u"上




李静
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rdrg109/subtitles-npcr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月30日(星期天) 中午12:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[rdrg109/subtitles-npcr] Is the pinyin of 都 incorrect in all these sentences? (Issue #904)





 
@Felicia0616 in #895 and in #892 have found two errors related to the pinyin of the character 都.
 
This motivated me to write some Python code to list all the groups whose zh-hans field contain the character 都 and whose pinyin field contain doū. The results are shown below. I wish someone familiar with pinyin could confirm that in all those groups, the pinyin of the character shouldn't be doū, but it should be dōu.
 - id: 41c6ed34-4e94-4f5c-922e-9a4934c5d030   zh-hans: 真不知道你每天都在想些什么。   pinyin: Zhēn bù zhīdào nǐ měitiān doū zài xiǎng xiē shénme. - id: 6cf3ea86-958c-4b2f-ae2b-0d0e1a9092fa   zh-hans: 这两天都是(1:坏:10)(2:消息:11)。   pinyin: Zhè liǎng tiān doū shì (1:huài) (2:xiāoxi). - id: c13fd1ae-7484-4a33-a25c-7e106d36b2e2   zh-hans: 刚来的时候你说过，如果每天都让你吃(1:中餐:17)，   pinyin: Gāng lái de shíhou nǐ shuōguò, rúguǒ měitiān doū ràng nǐ chī (1:zhōngcān), - id: 275226c4-7945-40b3-a873-2da73926e720   zh-hans: 是啊。我们从小到大都这样做。   pinyin: Shì a. Wǒmen cóngxiǎo dào dà doū zhèyàng zuò. - id: 41510ad8-ebdb-42e4-a5fe-7af801f90f37   zh-hans: 我觉得都很好。我爸爸妈妈他们也都是这样。   pinyin: Wǒ juéde dōu hěn hǎo. Wǒ bàba māmā tāmen yě doū shì zhèyàng. - id: f717a5e1-b607-4966-9ef8-1047fa16b530   zh-hans: 人们常说，如果你每天都认认真真地练，   pinyin: Rénmen cháng shuō, rúguǒ nǐ měitiān doū rènrèn zhēnzhēn de liàn, - id: 339eb456-e106-43bd-8e0c-c21e2a9d0d13   zh-hans: 也都是些老人。   pinyin: yě doū shì xiē lǎorén. - id: fb71b287-46b4-405a-a23d-ebbdd156d4b3   zh-hans: 因为爱好一样，不认识的人也都成了朋友。   pinyin: Yīnwèi àihào yīyàng, bù rènshi de rén yě doū chéngle péngyǒu. - id: b6540d97-ba6f-453d-a7be-41393f772eb8   zh-hans: 你每天都六点起床去锻炼，   pinyin: nǐ měitiān doū liù diǎn qǐchuáng qù duànliàn, - id: 12ceff94-285e-4846-b04a-cd71a869dd71   zh-hans: 黄山的松树和山峰也都很有特色。   pinyin: Huángshān de sōngshù hé shānfēng yě doū hěn yǒu tèsè. - id: f1da4184-d727-4053-a7fc-b08e9e131bda   zh-hans: 它每天都在热情地欢迎游黄山的朋友们。   pinyin: tā měitiān doū zài rèqíng de huānyíng yóu Huángshān de péngyǒumen. - id: 74cd1fc2-6ae2-4277-ac4d-b83e30628209   zh-hans: 他们也都很好。哥哥现在在一个中学打工，   pinyin: Tāmen yě doū hěn hǎo. Gēgē xiànzài zài yīgè zhōngxué dǎgōng, - id: 5d134402-fe07-43bd-9be5-a3c55edbaa70   zh-hans: 他来过两次，可是我都不在。   pinyin: Tā láiguò liǎng cì, kěshì wǒ doū bùzài. - id: 2702e021-5978-4c2d-9701-b040e3d27f6a   zh-hans: 现在我们都学习汉语，也都是汉语系的学生。   pinyin: Xiànzài wǒmen dōu xuéxí Hànyǔ, yě doū shì Hànyǔxì de xuéshēng.  
The Python code that was used to get these results are shown below.
 import os import yaml dir = './subtitles-new-practical-chinese-reader/sentences' os.chdir(dir) files = os.listdir(dir) for file in files:     with open(file) as f:          data = yaml.safe_load(f)          for obj in data:              if '都' in obj['zh-hans'] and 'doū' in obj['pinyin']:                  print(f"""- id: {obj['id']}   zh-hans: {obj['zh-hans']}   pinyin: {obj['pinyin']}""")

**Comment by rdrg109** [comment]
Done! f4ed060
