### ISSUE TITLE
collect them -- fetch them / pick them up

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#91]
https://github.com/rdrg109/subtitles-npcr/blob/4905cef6c4c5326e03470cf75f4f055425e8b8d2/sentences/44-2.yaml#L179C26-L179C33

**Comment by rdrg109** [comment]
The question here is: When we are talking about the action of obtaining an item from a group of lost items, what's the correct verb that we should use?

* collect
* fetch
* pick up

Let's use Google to sort this out

* `"airport" "lost items" "collect"` (3.840 results)
* `"airport" "lost items" "pick up"` (7.590 results)
* `"airport" "lost items" "fetch"` (367 results)

Drawing on those results, I am more inclined to use "pick up".

Done! 3cdc164
