### ISSUE TITLE
应该是shū fu 

### ISSUE THREAD

**Issue by Felicia0616** [rdrg109/subtitles-npcr#910]
https://github.com/rdrg109/subtitles-npcr/blob/87b7fe5f0b1d871bb66e3132a0e61de92c390239/sentences/26-text.yaml#L118

**Comment by rdrg109** [comment]
Done! 22dc056

@Felicia0616 I think that 不 should be in 4th tone in this sentence. Am I right?

https://github.com/rdrg109/subtitles-npcr/blob/22dc056ce74cb693bac1f1f2b27e1dff5479caba/sentences/26-text.yaml#L116-L120
