### ISSUE TITLE
Some students -- A pupil also

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#92]
https://github.com/rdrg109/subtitles-npcr/blob/4905cef6c4c5326e03470cf75f4f055425e8b8d2/sentences/44-2.yaml#L184C7-L184C20

**Comment by rdrg109** [comment]
Done! d0a31ee.

More information on the difference between "student" and "pupil" in https://github.com/rdrg109/subtitles-npcr/issues/86#issuecomment-1657067915 .
