### ISSUE TITLE
请坐。

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#966]
https://github.com/rdrg109/subtitles-npcr/blob/781c13fd10a68e4762ef1c1ba0bc0191659bc396/sentences/45-text-1.yaml#L58

**Comment by rdrg109** [comment]
本来的字幕用“逗号”。难道你认为本来的字幕有错误吗？我也这样想

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/cc882fe5-c5dc-45ca-b6ea-880bebec17e7)

77eaaa3

**Comment by fhxshrs** [comment]
因为课文里是句号。
