### ISSUE TITLE
汉语水平考试八级 -- 新汉语水平六级考试

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#968]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/45-text-1.yaml#L148C18-L148C26

**Comment by rdrg109** [comment]
There's difference between the video and the text. I have added the two sentences. 8d776ab

Video

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/c5462ee8-8a73-4d1f-a6c2-90ed3de56c52)

Text

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/09a3185e-0a65-4774-ae0e-ad1990a6f6c1)
