### ISSUE TITLE
负责联系亚洲——

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#970]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/45-text-2.yaml#L88

**Comment by rdrg109** [comment]
For the  record, the book shows —— while the video shows a comma. I've created one version for the video and other version for the book: 754fa9b

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/44996ad1-74af-47ee-8428-3d0938fbfd88)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/4226a0c1-aeda-4627-8bbd-cd6e370a3487)
