### ISSUE TITLE
两个“她”

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#977]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-1.yaml#L268

**Comment by rdrg109** [comment]
This is a difference between the hard-coded subtitles of the videos and [El Nuevo Libro de Chino Práctico (Spanish) (4th volume)](https://wikidata.org/wiki/Q118106264). I've created a new version: f8f1b45

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/e49d8395-14f9-4d44-b4e4-5445fe694acc)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/f0fbd6b5-a7c3-440f-bef2-47e45b83659c)
