### ISSUE TITLE
她

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#978]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-1.yaml#L317-L320

**Comment by rdrg109** [comment]
This is a difference between the hard-coded subtitles of the videos and [El Nuevo Libro de Chino Práctico (Spanish) (4th volume)](https://wikidata.org/wiki/Q118106264). I've created a new version: d5e6acb

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/6f85bfee-7e38-4715-90e5-fed3108b11b5)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/4ffe9865-281c-42b9-9b62-3fb741567fc5)
