### ISSUE TITLE
她

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#979]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-1.yaml#L322-L325

**Comment by rdrg109** [comment]
This is a difference between the hard-coded subtitles of the videos and [El Nuevo Libro de Chino Práctico (Spanish) (4th volume)](https://wikidata.org/wiki/Q118106264). I've created a new version: 75dd4a7

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/62afeb49-d56f-4870-8bb0-91657b128dcc)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/92fa79b8-ed24-46e8-af44-ef686dbd96cf)
