### ISSUE TITLE
两--二

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#980]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-2.yaml#L17-L21

**Comment by rdrg109** [comment]
Both the video and [El Nuevo Libro de Chino Práctico (Spanish) (vol. 4) (ed. 1)](https://wikidata.org/wiki/Q118106264) show 二年级, so there should be a single version. Done! 5542ffd

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/ac99d0f4-8480-4465-95cf-c75a6cfbf772)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/6e329b73-e486-4039-b528-4f8feda5c88a)
