### ISSUE TITLE
没有“很”

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#981]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-2.yaml#L37-L41

**Comment by rdrg109** [comment]
Both the video and [El Nuevo Libro de Chino Práctico (Spanish) (vol. 4) (ed. 1)](https://wikidata.org/wiki/Q118106264) don't show 很. I've edited the file: 35a8958

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/d70206d7-066a-461e-a092-0392455df4a2)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/1142eeca-7ebb-46a2-93b5-0298c69779ff)
