### ISSUE TITLE
是在海边

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#983]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-2.yaml#L162-L166

**Comment by rdrg109** [comment]
Both the video and [El Nuevo Libro de Chino Práctico (Spanish) (vol. 4) (ed. 1)](https://wikidata.org/wiki/Q118106264) show 是, so there should be a single version. I've edited the file: ec18214

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/c74b0f5c-7763-4519-b7fe-317409fee038)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/b9733afe-b354-4a4c-9305-d6b8ceb8eaa8)
