### ISSUE TITLE
这句话课文里没有

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#990]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-2.yaml#L282-L286

**Comment by rdrg109** [comment]
This sentence doesn't appear in [El Nuevo Libro de Chino Práctico (Spanish) (vol. 4) (ed. 1)](https://wikidata.org/wiki/Q118106264), but still appear in the video, so we cannot delete it. I've added a `context` indicator to make this clear: f8d1d5e

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/dba99df0-9bd0-488c-8c35-e5e207552b7e)

[output.webm](https://github.com/rdrg109/subtitles-npcr/assets/74389646/12bc32bd-fa52-4bc5-a29d-6c8c223712a5)
