### ISSUE TITLE
学会了

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/subtitles-npcr#995]
https://github.com/rdrg109/subtitles-npcr/blob/8f90d8f7dfb2ec80bfe2729b2e398b85b3d6800d/sentences/46-text-2.yaml#L412-L416

**Comment by rdrg109** [comment]
The video doesn't show 了 while the text shows 了. This problem occurs in two sentences. I've created two versions for these two sentences: 581ad9d

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/aee6eb04-d9ff-47a0-a5cc-c7932e6841be)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/cde832bd-4338-4d26-9bbb-0b262fceedd6)

![image](https://github.com/rdrg109/subtitles-npcr/assets/74389646/2d84f0e0-3d4b-4f14-b7e6-075afa2ba79e)
